name: 'GitHub Actions Debugger'
description: 'Output all environment variables for debug purpose'
author: 'Sebastian Rockwell'
inputs: 
  varname:
    description: 'More variable to explore'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.varname }}
